---
version: "3.7"

secrets:
  config_json:
    file: ./src/secrets/config.json
  admin_fullchain_pem:
    file: ./src/secrets/admin_fullchain.pem
  admin_privkey_pem:
    file: ./src/secrets/admin_privkey.pem
  phish_fullchain_pem:
    file: ./src/secrets/phish_fullchain.pem
  phish_privkey_pem:
    file: ./src/secrets/phish_privkey.pem

services:
  gophish:
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: cisagov/gophish
    init: true
    restart: always
    ports:
      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 8080
        published: 3380
        protocol: tcp
        mode: host
    secrets:
      - source: config_json
        target: config.json
      - source: admin_fullchain_pem
        target: admin_fullchain.pem
      - source: admin_privkey_pem
        target: admin_privkey.pem
      - source: phish_fullchain_pem
        target: phish_fullchain.pem
      - source: phish_privkey_pem
        target: phish_privkey.pem
